language: php

sudo: required

matrix:
  include:
    - php: 7.2
      env: SW_VERSION="4.5.2" DAEMONIZE=1 SCAN_CACHEABLE=(true)
    - php: 7.3
      env: SW_VERSION="4.5.2" DAEMONIZE=1 SCAN_CACHEABLE=(true)
    - php: 7.4
      env: SW_VERSION="4.5.2" DAEMONIZE=1 SCAN_CACHEABLE=(true)

services:
  - mysql
  - redis
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash .travis/swoole.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis/ci.ini
  - bash .travis/setup.mysql.sh
  - docker run -d --restart=always --name rabbitmq -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 rabbitmq:management-alpine

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update -o
  - php bin/hyperf.php
  - php bin/hyperf.php start
  - sleep 10

script:
  - composer test
